/**
 * PRD (product spec) generator.
 *
 * Turns a catalog idea into a downloadable, Kiro-style spec that a builder (or
 * an AI coding agent) can use as the context for building the app. The format
 * mirrors this repo's own `.kiro/specs/*` layout: Overview, Requirements
 * (user stories with EARS-style acceptance criteria), Design + Data Model
 * (Supabase tables), an implementation task checklist, and stretch goals.
 *
 * Pure and dependency-free so it is trivially unit-testable and can run in a
 * Route Handler. All inputs are coerced defensively because `features`,
 * `data_model`, and `stretch_goals` arrive as untyped JSON from Postgres.
 *
 * Copy discipline: this output is user-facing, so it contains zero em-dashes
 * (hyphens only), per the project's design rules.
 */

export interface PrdTable {
  name: string;
  purpose: string;
}

export interface PrdIdea {
  title: string;
  tagline: string;
  description: string;
  rarityTier: string;
  features: string[];
  dataModel: PrdTable[];
  stretchGoals: string[];
}

const RARITY_LABEL: Record<string, string> = {
  common: "Common",
  rare: "Rare",
  super_rare: "Super Rare",
};

/** URL/file-safe slug from a title (kept for callers that want a nice name). */
export function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "idea"
  );
}

/** Coerce an unknown JSON value into a string array (dropping non-strings). */
export function toStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is string => typeof v === "string" && v.length > 0);
}

/** Coerce an unknown JSON value into a PrdTable array. */
export function toTableArray(value: unknown): PrdTable[] {
  if (!Array.isArray(value)) return [];
  return value.flatMap((v) => {
    if (v && typeof v === "object" && "name" in v && "purpose" in v) {
      const name = (v as Record<string, unknown>).name;
      const purpose = (v as Record<string, unknown>).purpose;
      if (typeof name === "string" && typeof purpose === "string") {
        return [{ name, purpose }];
      }
    }
    return [];
  });
}

/** First word of a feature, lower-cased, used to phrase a user story. */
function featureAsStory(feature: string): string {
  const lead = feature.charAt(0).toLowerCase() + feature.slice(1);
  return `I want to ${lead}`;
}

/**
 * Builds the full Kiro-style spec markdown for an idea. Sections degrade
 * gracefully when the structured fields are empty.
 */
export function buildPrdMarkdown(idea: PrdIdea): string {
  const rarity = RARITY_LABEL[idea.rarityTier] ?? idea.rarityTier;
  const lines: string[] = [];

  // Header
  lines.push(`# ${idea.title} - Product Spec`);
  lines.push("");
  if (idea.tagline) lines.push(`> ${idea.tagline}`);
  lines.push("");
  lines.push(
    `Rarity: ${rarity}. Generated by Kiro Idea Vault as a starting spec for a fullstack app built on Next.js and Supabase.`,
  );
  lines.push("");

  // Overview
  lines.push("## Overview");
  lines.push("");
  lines.push(idea.description);
  lines.push("");

  // Goals
  lines.push("## Goals");
  lines.push("");
  lines.push("- Ship a working fullstack app that a beginner can complete.");
  lines.push("- Use Supabase for auth and data, with Row Level Security on every table.");
  lines.push("- Keep the scope small: build the core loop first, then polish.");
  lines.push("");

  // Target users
  lines.push("## Target Users");
  lines.push("");
  lines.push(
    "Individual signed-in users managing their own data. Each user only sees and edits their own rows, enforced by RLS.",
  );
  lines.push("");

  // Tech stack
  lines.push("## Tech Stack");
  lines.push("");
  lines.push("- Next.js (App Router) with TypeScript.");
  lines.push("- Tailwind CSS for styling, mobile-first.");
  lines.push("- Supabase: Auth (email/password), Postgres, and Row Level Security.");
  lines.push(
    "- Supabase client via `@supabase/supabase-js` and `@supabase/ssr` for session handling.",
  );
  lines.push("");

  // Requirements
  lines.push("## Requirements");
  lines.push("");
  if (idea.features.length === 0) {
    lines.push("_Define the core user stories for this app._");
    lines.push("");
  } else {
    idea.features.forEach((feature, i) => {
      lines.push(`### Requirement ${i + 1}: ${feature}`);
      lines.push("");
      lines.push(`**User story:** As a signed-in user, ${featureAsStory(feature)}.`);
      lines.push("");
      lines.push("**Acceptance criteria:**");
      lines.push(
        `- WHEN the user performs this action, THEN the app SHALL persist the result to Supabase and reflect it in the UI.`,
      );
      lines.push(
        "- WHEN the user is not signed in, THEN the app SHALL require authentication first.",
      );
      lines.push(
        "- WHEN the data belongs to another user, THEN RLS SHALL prevent access.",
      );
      lines.push("");
    });
  }

  // Data model
  lines.push("## Data Model (Supabase)");
  lines.push("");
  lines.push(
    "All tables live in the `public` schema with RLS enabled. User-owned tables carry a `user_id uuid references auth.users(id)` column and a policy scoping rows to `auth.uid()`.",
  );
  lines.push("");
  if (idea.dataModel.length === 0) {
    lines.push("_Define the tables this app needs._");
    lines.push("");
  } else {
    idea.dataModel.forEach((table) => {
      lines.push(`### \`${table.name}\``);
      lines.push("");
      lines.push(table.purpose);
      lines.push("");
    });
  }

  // Implementation tasks
  lines.push("## Implementation Tasks");
  lines.push("");
  lines.push("- [ ] Scaffold a Next.js App Router project with TypeScript and Tailwind.");
  lines.push("- [ ] Create a Supabase project and wire up env vars.");
  lines.push("- [ ] Add email/password auth with `@supabase/ssr` and protect routes.");
  idea.dataModel.forEach((table) => {
    lines.push(`- [ ] Create the \`${table.name}\` table with RLS policies.`);
  });
  idea.features.forEach((feature) => {
    lines.push(`- [ ] Build: ${feature}.`);
  });
  lines.push("- [ ] Handle loading, empty, and error states for each view.");
  lines.push("- [ ] Deploy and test the full flow end to end.");
  lines.push("");

  // Stretch goals
  lines.push("## Stretch Goals");
  lines.push("");
  if (idea.stretchGoals.length === 0) {
    lines.push("_Optional extensions once the core app works._");
  } else {
    idea.stretchGoals.forEach((goal) => lines.push(`- ${goal}`));
  }
  lines.push("");

  return lines.join("\n");
}
